[package]
name = "netcdf3"
version = "0.1.0"
authors = ["Julien BONTE <julien.bonte@protonmail.com>"]
edition = "2018"

description = "A Rust implementation of NetCDF-3 file format"
license = "MIT"
repository = "https://github.com/julienbonte/netcdf3"
keywords = ["netcdf"]
readme = "README.md"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
byteorder = "1.3.4"
nom = "5.1.1"

[dev-dependencies]
tempdir = "0.3.7"

[badges]
appveyor = { repository = "julienbonte/netcdf3" }
maintenance = { status = "experimental" }
